---
title: "5th Chapter Book"
author: "Mykola Dereva"
date: "1/27/2021"
output: html_document
---

```{r}
library(rethinking)
library(tidyverse)
```


```{r}
# load data and copy

data(WaffleDivorce)
d <- WaffleDivorce

# standardize variables
d$D <- standardize( d$Divorce )
d$M <- standardize( d$Marriage )
d$A <- standardize( d$MedianAgeMarriage )
```



```{r}
m5.1 <- quap(
  alist(
    D ~ dnorm(mean, sigma),
    mean <- a + bA*A,
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d
)
```


```{r}
set.seed(10)
prior <- extract.prior( m5.1 )
mu <- link(m5.1 , post = prior, data = list(A = c(-2,2)))
plot(NULL , xlim = c(-2,2), ylim = c(-2,2) )
for (i in 1:50 ) lines(c(-2,2) , mu[i,] , col = col.alpha("black",0.4) )
```


```{r}
# compute percentile interval of mean
A_seq <- seq( from = -3, to = 3.2 , length.out = 30)
mu <- link(m5.1, data = data.frame(A = A_seq))
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)


# plot it all
plot(D ~ A, data = d, col = rangi2)
lines(A_seq, mu.mean, lwd = 2)
shade(mu.PI, A_seq)
```

```{r}
precis(m5.1)
```



```{r}
m5.2 <- quap(
  alist(
    D ~ dnorm(mu , sigma),
    mu <- a + bM * M,
    a ~ dnorm(0, 0.2),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d 
)
```


```{r}
# compute percentile interval of mean
M_seq <- seq( from = -3, to = 3.2 , length.out = 50)
mu <- link(m5.2, data = data.frame(M = M_seq))
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI)


# plot it all
plot(D ~ M, data = d, col = rangi2)
lines(M_seq, mu.mean, lwd = 2)
shade(mu.PI, M_seq)
```

```{r}
precis(m5.2)
```


```{r}
library(dagitty)

dag5.1 <- dagitty("dag{ A -> D; A -> M; M -> D }" )
coordinates(dag5.1) <- list(x = c(A = 0, D = 1, M = 2) ,
                            y = c(A = 0, D = 1, M = 0))
drawdag( dag5.1 )
```

```{r}
d %>% select(A, M, D) %>% 
  cor()
```


```{r}
DMA_dag2 <- dagitty('dag{ D <- A -> M }')
impliedConditionalIndependencies( DMA_dag2 )
```





```{r}
m5.3 <- quap(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + bA*A + bM*M,
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d
)
```

```{r}
precis(m5.3)
```

```{r}
plot(coeftab(m5.1,m5.2,m5.3), par = c("bA","bM") )
```




```{r}
m5.4 <- quap(
  alist(
    M ~ dnorm(mu, sigma),
    mu <- a + bAM * A,
    a ~ dnorm(0, 0.2) ,
    bAM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data = d
)

```



```{r}
# call link without specifying new data
# so it uses original data
mu <- link(m5.3)
# summarize samples across cases
mu_mean <- apply(mu, 2, mean)
mu_PI <- apply(mu, 2, PI)
# simulate observations
# again no new data, so uses original data
D_sim <- sim(m5.3, n = 1e4)
D_PI <- apply(D_sim, 2, PI)
```

```{r}
plot(mu_mean ~ d$D , col = rangi2 , ylim = range(mu_PI),
     xlab = "Observed divorce" , ylab = "Predicted divorce" )
abline(a = 0, b = 1, lty = 2)
for (i in 1:nrow(d) ) lines(rep(d$D[i],2), mu_PI[,i], col = rangi2)
```





```{r}
m5.3_A <- quap(
alist(
  ## A -> D <- M
    D ~ dnorm(mu, sigma),
    mu <- a + bM*M + bA*A,
    a ~ dnorm( 0 , 0.2 ),
    bM ~ dnorm( 0 , 0.5 ),
    bA ~ dnorm( 0 , 0.5 ),
    sigma ~ dexp( 1 ),
  ## A -> M
    M ~ dnorm( mu_M , sigma_M ),
    mu_M <- aM + bAM*A,
    aM ~ dnorm( 0 , 0.2 ),
    bAM ~ dnorm( 0 , 0.5 ),
    sigma_M ~ dexp( 1 )
  ) , data = d 
)
```



```{r}
A_seq <- seq( from = -2, to = 2, length.out = 30)

# prep data 
sim_dat <- data.frame(A = A_seq)
# simulate M and then D, using A_seq
s <- sim(m5.3_A, data = sim_dat, vars = c("M","D"))

plot( sim_dat$A , colMeans(s$D) , ylim = c(-2, 2) , type = "l",
      xlab = "manipulated A" , ylab = "counterfactual D" )
shade( apply(s$D,2,PI) , sim_dat$A )
mtext( "Total counterfactual effect of A on D" )
```



```{r}
# new data frame, standardized to mean 26.1 and std dev 1.24
sim2_dat <- data.frame( A = (c(20,30) - 26.1)/1.24 )
s2 <- sim( m5.3_A , data = sim2_dat, vars = c("M","D") )
mean( s2$D[,2] - s2$D[,1] )
```



```{r}
sim_dat <- data.frame( M = seq(from = -2, to = 2, length.out = 30) , A = 0 )
s <- sim( m5.3_A , data = sim_dat , vars = "D" )
plot( sim_dat$M , colMeans(s) , ylim = c(-2,2) , type = "l" ,
      xlab = "manipulated M" , ylab = "counterfactual D" )
shade( apply(s,2,PI) , sim_dat$M )
mtext( "Total counterfactual effect of M on D" )
```

# 5.2. Masked relationship

```{r}
rm(list = ls())

library(rethinking)
library(tidyverse)
```


```{r}
data(milk)
d <- milk

d$K <- standardize( d$kcal.per.g )
d$N <- standardize( d$neocortex.perc )
d$M <- standardize( log(d$mass) )
```

```{r}
dcc <- d %>% 
  drop_na(K, N, M)
```


```{r}
m5.5_draft <- quap(
  alist(
    K ~ dnorm(mu, sigma),
    mu <- a + bN*N,
    a ~ dnorm(0, 1),
    bN ~ dnorm(0, 1),
    sigma ~ dexp(1)
  ) , data = dcc 
)
```


```{r}
prior <- extract.prior(m5.5_draft)
xseq <- c(-2, 2)
mu <- link(m5.5_draft, post = prior, data = list(N = xseq))

plot(NULL, xlim = xseq , ylim = xseq)
for (i in 1:50) lines(xseq, mu[i,], col = col.alpha("black", 0.3) )
```



```{r}
m5.5 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bN*N ,
    a ~ dnorm( 0 , 0.2 ) ,
    bN ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data = dcc
)
```

```{r}
precis(m5.5)
```

```{r}
prior <- extract.prior(m5.5)
xseq <- c(-2, 2)
mu <- link(m5.5, post = prior, data = list(N = xseq))

plot(NULL, xlim = xseq , ylim = xseq)
for (i in 1:50) lines(xseq, mu[i,], col = col.alpha("black", 0.3) )
```





```{r}
xseq <- seq(from = min(dcc$N) - 0.15, to = max(dcc$N) + 0.15 , length.out = 30)
mu <- link(m5.5 , data = list(N = xseq) )
mu_mean <- apply(mu,2,mean)
mu_PI <- apply(mu, 2, PI)
plot( K ~ N, data = dcc )
lines( xseq, mu_mean, lwd = 2)
shade(mu_PI, xseq)
```




```{r}
m5.6 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bM*M ,
    a ~ dnorm( 0 , 0.2 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data=dcc
)

precis(m5.6)
```




```{r}
m5.7 <- quap(
  alist(
    K ~ dnorm( mu , sigma ) ,
    mu <- a + bN*N + bM*M ,
    a ~ dnorm( 0 , 0.2 ) ,
    bN ~ dnorm( 0 , 0.5 ) ,
    bM ~ dnorm( 0 , 0.5 ) ,
    sigma ~ dexp( 1 )
  ) , data = dcc)

precis(m5.7)
```



```{r}
plot( coeftab( m5.5 , m5.6 , m5.7 ) , pars=c("bM","bN") )
```


```{r}
pairs( ~ K + M + N , dcc )
```




# 5.3. Categorical variables



```{r}
data(Howell1)
d <- Howell1
```

```{r}
d$sex <- ifelse( d$male == 1 , 2 , 1 )
```


```{r}
m5.8 <- quap(
  alist(
    height ~ dnorm(mu , sigma) ,
    mu <- a[sex] ,
    a[sex] ~ dnorm(178 , 20) ,
    sigma ~ dunif(0 , 50)
    ) , data = d )

precis(m5.8, depth = 2)
```


```{r}
post <- extract.samples(m5.8)
post$diff_fm <- post$a[,1] - post$a[,2]
precis( post , depth = 2 )
```




```{r}
data(milk)
d <- milk
levels(d$clade)
```

```{r}
d$clade_id <- as.integer( d$clade )
```




```{r}
d$K <- standardize( d$kcal.per.g )
m5.9 <- quap(
  alist(
    K ~ dnorm( mu , sigma ),
    mu <- a[clade_id],
    a[clade_id] ~ dnorm( 0 , 0.5 ),
    sigma ~ dexp( 1 )
  ) , data = d 
)



labels <- paste( "a[" , 1:4 , "]:" , levels(d$clade) , sep = "" )
plot( precis( m5.9 , depth = 2 , pars = "a" ) , labels = labels ,
xlab = "expected kcal (std)" )
```

